### ISSUE TITLE
[Suggestion] Add translation file for new stuff (creatures and other)

### ISSUE THREAD

**Issue by Blueberryy** [Conga0/Mo_Creeps#1]
I can help with russian translation if needed

**Comment by Conga0** [comment]
Hello!

If you would like to translate the mod into Russian I would appreciate it greatly, but there is a lot of internal text to take care of.

Just incase you're unfamiliar with the process, here's some things to take note of:

Anytime you see **\n** in a description, it means it's a linebreak, similar to pressing enter on your keyboard to go to the next line of text down.
The leftmost text is the translation key, for example **spell_mocreep_split_shot_name**, these are simply the internal reference for the text and do not need to be translated, any text besides the translation keys, typically in quotations, is the actual text.

Additionally for the lines which say "Cave quid volunt", for example in the translation key spell_mocreep_bungal_shift_desc, this is latin and I'll leave it up to your judgement whether to translate it or not, but the intention behind "Cave quid volunt" is "be careful what you wish for".


I've attached a txt file below containing all the lines which can be translated

[translationkeys.txt](https://github.com/Conga0/Mo_Creeps/files/9908198/translationkeys.txt)

I'm new to this process, but I hope I've made things easy for you.
Once you're finished translating, send me the translated list through any means fitting for you and I can implement it into the mod.

Thankyou.

**Comment by Blueberryy** [comment]
sure i will do it soon
conga lads! [![conga!](https://thumbs.gfycat.com/BowedGlisteningJunebug-size_restricted.gif)](https://thumbs.gfycat.com/BowedGlisteningJunebug-size_restricted.gif)

**Comment by Blueberryy** [comment]
Okay, i think i made it by using Modern CSV 
[translationkeys.txt](https://github.com/Conga0/Mo_Creeps/files/9920490/translationkeys.txt)

**Comment by Conga0** [comment]
Thankyou!

I've just finished implementing the translations and everything seems to be working, I'll push the update shortly

**Comment by Blueberryy** [comment]
Nice! Now you can take care of others later
